# Generated by Django 4.1.5 on 2023-01-05 20:43

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(help_text='Informe seu nome completo', max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Seu melhor e-mail. Será usado para login também.', max_length=254, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este username.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e os símbolos @/./+/-/_ são permitidos.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Usuário')),
                ('is_staff', models.BooleanField(default=False, help_text='Pode logar no Admin', verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Usuário com acesso irrestrito no sistema.', verbose_name='Usuário administrador')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque esta opção em vez de deletar o usuário.', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de cadastro')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(blank=True, choices=[('adm_clipse_access', 'Administrador Clipse'), ('admn_clinic_access', 'Administrador Clinica'), ('user_clipse_access', 'Usuário Clipse'), ('user_clinic_access', 'Usuário Clinica')], max_length=100, null=True, verbose_name='Nivel de permissão do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', helpers.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social')),
                ('cpf', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='Cidade')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número da casa')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
